
# project_id must be the first line
project_id = "fzuwsjxjymwcjsbpwfsl"

[[functions]]
name = "process-youtube-news"
verify_jwt = false

[[functions]]
name = "sync-youtube-channels"
verify_jwt = false
