
project_id = "fzuwsjxjymwcjsbpwfsl"
api_schema = "public"

[functions.fetch-ai-news]
verify_jwt = false

[functions.analyze-news]
verify_jwt = false

[functions.generate-daily-summary]
verify_jwt = false

[functions.chat-with-assistant]
verify_jwt = false
