
project_id = "fzuwsjxjymwcjsbpwfsl"
serve_dir = "/"

[global.env]
SUPABASE_URL = "env:SUPABASE_URL"
SUPABASE_SERVICE_ROLE_KEY = "env:SUPABASE_SERVICE_ROLE_KEY"
EVENT_REGISTRY_API_KEY = "env:EVENT_REGISTRY_API_KEY"
NEWS_API_KEY = "env:NEWS_API_KEY"
