
project_id = "wnwhlqmeshtreeebxior"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[proxy]
check_database = false
reference_id = null

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[functions]
enabled = true
port = 54324
timeout_seconds = 30
default_runtime = "deno"

[functions.verify]
enabled = true
command = "supabase-functions-verify"
params = "."

[inbucket]
enabled = true
port = 54325

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
