
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnwhlqmeshtreeebxior.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indud2hscW1lc2h0cmVlZWJ4aW9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2NTcyNTQsImV4cCI6MjA1MjIzMzI1NH0.XZuyJBEv2L16g-C3ejSw9MfA0A-VAlKvbiAjrlvfGrs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
